services:
  - type: web
    name: Simulador-de-Plan-de-Ahorro-Automotriz
    env: pytho
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn mi_sitio.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mi_sitio.settings