# Generated by Django 6.0.4 on 2026-05-28 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tipo_empleo', models.CharField(choices=[('dependencia', 'Relación de Dependencia'), ('independiente', 'Trabajador Independiente')], max_length=20)),
                ('antiguedad', models.IntegerField()),
                ('ingreso', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(choices=[('baja', 'Gama Baja'), ('media', 'Gama Media'), ('alta', 'Gama Alta'), ('premium', 'Premium')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('img', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular_nombre', models.CharField(max_length=100)),
                ('titular_dni', models.CharField(max_length=20)),
                ('titular_telefono', models.CharField(max_length=20)),
                ('titular_email', models.EmailField(max_length=254)),
                ('titular_edad', models.IntegerField()),
                ('titular_ingreso', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan_tipo', models.CharField(choices=[('70/30', 'Plan 70/30'), ('80/20', 'Plan 80/20')], max_length=10)),
                ('cantidad_cuotas', models.IntegerField(default=84)),
                ('es_calificado', models.BooleanField(default=False)),
                ('valor_cuota_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('motivos_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('garante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mi_app.garante', verbose_name='Garante')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mi_app.vehiculo', verbose_name='Vehículo')),
            ],
        ),
    ]
